// Package {{.Package}}
// @file:types.go
// @version:{{.Version}}
// @date:{{.Date}}
// Code generated by goctl-resty-client. DO NOT EDIT.
package {{.Package}}
//go:generate fieldalignment -fix types.go
//begin
type(
    {{range .Type}}
    {{range .Docs -}}
    {{.}}
    {{- end}}
    {{.RawName}} struct{
    {{- if .Members}}
    {{if .Docs}} {{range .Docs}}
    {{- . -}}
    {{- end}}{{- end}}
    {{- range .Members}}
        {{- if .IsInline}}
            {{.Type.RawName}} {{if .Comment}}{{.Comment}}{{- end}}
        {{- else}}
            {{.Name}} {{.Type.RawName}} {{if .Tag}}{{.Tag}}{{- end}} {{if .Comment}}{{.Comment}}{{- end}}
        {{- end}}
    {{- end}}
    {{- end}}
    }
    {{- end}}
)

{{- range $ind, $elem := .Type}}

func (t *{{$elem.RawName}}) Reset(){
    *t={{$elem.RawName}}{}
}
{{range $elem.Members}}
{{- if isPublic $elem.RawName}}
{{if not .IsInline}}
func (t *{{$elem.RawName}}) Set{{.Name}}(v {{.Type.RawName}}) *{{$elem.RawName}}{
    t.{{.Name}}=v
    return t
}

func (t *{{$elem.RawName}}) Get{{.Name}}() {{.Type.RawName}}{
    return t.{{.Name}}
}
{{- end}}
{{- end}}
{{- end}}
{{- end}}
