// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code uint32 `json:"code"`
	Msg  string `json:"msg"`
}

type HelloRequest struct {
	ID uint64 `json:"id,optional" path:"id"` //系统方案ID
}
