// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	hello "github.com/mengdj/goctl-rest-client/examples/test/internal/handler/hello"
	world "github.com/mengdj/goctl-rest-client/examples/test/internal/handler/world"
	"github.com/mengdj/goctl-rest-client/examples/test/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/app/test/hello/:id",
				Handler: hello.HelloHandler(serverCtx),
			},
		}, rest.WithTimeout(30000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/app/test/world/:id",
				Handler: world.HelloHandler(serverCtx),
			},
		}, rest.WithTimeout(30000*time.Millisecond),
	)
}
