// Code generated by goctl. DO NOT EDIT.
package types

type HelloRequest struct {
	ID   uint64 `json:"id,optional" path:"id"` //系统方案ID
	More string `json:",optional"`             //测试
}

type Response struct {
	Code uint32 `json:"code"`
	Msg  string `json:"msg"`
}

type WorldRequest struct {
	ID   uint64 `json:"id,optional" path:"id"` //系统方案ID
	More string `json:",optional"`             //测试
}
