// Package client
// @file:types.go
// @version:v0.0.3
// @date:2023-02-27 09:28:38.83772833 +0800 CST m=+0.010425701
// Code generated by goctl-resty-client. DO NOT EDIT.
package client

// begin
//
//go:generate fieldalignment -fix types.go
type (
	Response struct {
		Code uint32 `json:"code"`
		Msg  string `json:"msg"`
	}

	HelloRequest struct {
		ID   uint64 `json:"id,optional" path:"id"` //系统方案ID
		More string `json:",optional"`             //测试
	}
)

func (t *Response) Reset() {
	*t = Response{}
}

func (t *Response) SetCode(v uint32) *Response {
	t.Code = v
	return t
}

func (t *Response) GetCode() uint32 {
	return t.Code
}

func (t *Response) SetMsg(v string) *Response {
	t.Msg = v
	return t
}

func (t *Response) GetMsg() string {
	return t.Msg
}

func (t *HelloRequest) Reset() {
	*t = HelloRequest{}
}

func (t *HelloRequest) SetID(v uint64) *HelloRequest {
	t.ID = v
	return t
}

func (t *HelloRequest) GetID() uint64 {
	return t.ID
}

func (t *HelloRequest) SetMore(v string) *HelloRequest {
	t.More = v
	return t
}

func (t *HelloRequest) GetMore() string {
	return t.More
}
